export interface Article {
  id: string;
  title: string;
  source: string;
  author: string;
  summary: string;
  imageUrl: string;
  category: string;
  publishedAt: number;
  url: string;
  likes: number;
  comments: number;
  bookmarks: number;
  content?: string; 
}

// Function to fetch article content from URL
export async function fetchArticleContent(url: string): Promise<string> {
  try {
    const proxyUrl = "https://corsproxy.io/?";
    const response = await fetch(proxyUrl + encodeURIComponent(url));
    if (!response.ok) throw new Error("Network error");

    const html = await response.text();
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');

    // Target the main content area specifically
    const container = doc.querySelector('article, .article-body, .entry-content, #main-content');
    
    if (!container) return "Readable content not found.";

    // Extract only <p> tags
    const paragraphs = container.querySelectorAll('p');
    
    // 3. Filter and Clean
    const cleanParagraphs = Array.from(paragraphs)
      .map(p => p.textContent?.trim() || "")
      // Filter out typical junk (Social links, timestamps, short UI text)
      .filter(text => 
        text.length > 40 && // Ignore very short fragments
        !text.includes("ShareComments") && 
        !text.includes("Follow us on") &&
        !/^\d{2}:\d{2}/.test(text) // Ignore text starting with timestamps like 12:32
      );

    return cleanParagraphs.join('\n\n') || 'No significant text content found.';
  } catch (error) {
    console.error('Scraping error:', error);
    return 'Error loading article content.';
  }
}

export const articlesData: Article[] = [
  // Main Feed Articles
  {
    id: crypto.randomUUID(),
    title: "Michael Carrick press conference LIVE Man United injury updates and Newcastle team news",
    source: "MEN",
    author: "Jack Flintham",
    summary: "Manchester United interim head coach Michael Carrick will speak to the media this afternoon ahead of the Premier League trip to Newcastle",
    imageUrl: "https://i2-prod.manchestereveningnews.co.uk/incoming/article33519841.ece/ALTERNATES/s615/0_GettyImages-2263879055.jpg",
    category: "Manchester United",
    publishedAt: 1772539368660,
    url: "https://www.manchestereveningnews.co.uk/sport/football/football-news/michael-carrick-press-conference-live-33519712",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Brighton boss Hurzeler calls out Arsenal for time-wasting",
    source: "Metro",
    author: "metro.co.uk",
    summary: "Fabian Hurzeler wants referees to clamp down on Arsenal's delays at corners and throw-ins, arguing, \"when Arsenal have a corner and they are leading, sometimes they spend over a minute just to take a corner.\"",
    imageUrl: "https://metro.co.uk/wp-content/uploads/2026/03/GettyImages-2261156745_1772536572.jpg?quality=90&strip=all&w=1200&h=630&crop=1",
    category: "Premier League",
    publishedAt: 1772536564000,
    url: "https://metro.co.uk/2026/03/03/brighton-boss-takes-swipe-arsenal-calls-major-rule-change-27203797/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Pep Guardiola reveals Erling Haaland 'feels much better' ahead of Man City vs. Forest",
    source: "Evening Standard Football",
    author: "Oli Gent",
    summary: "\"He feels much better, but yesterday we didn't train and now we have training. We'll decide today,\" Guardiola said of the forward.\n\n\"The same\" applies to Nico O'Reilly, who hobbled off in the victory in Yorkshire with an ankle problem.",
    imageUrl: "https://static.standard.co.uk/2026/02/11/23/37/Manchester-City-v-Fulham-Premier-League-pfchnzjv.jpeg?width=1200&auto=webp&crop=3%3A2",
    category: "Top Headlines",
    publishedAt: 1772542016739,
    url: "https://www.standard.co.uk/sport/football/man-city-haaland-injury-update-guardiola-update-b1273216.html",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Jeremy Jacquet to have shoulder op at Rennes before £60m Liverpool summer move",
    source: "DaveOCKOP",
    author: "Liam McPherson",
    summary: "Rennes confirm Jacquet will have shoulder surgery after his Lens injury, with rehab timing set to let him join Liverpool this summer fully fit and ready to compete for a first-team spot.",
    imageUrl: "https://www.daveockop.com/wp-content/uploads/2026/02/0fab81ce12e48a0794275e1d82449fb1_1071923591.webp",
    category: "Liverpool",
    publishedAt: 1772538642000,
    url: "https://www.daveockop.com/latest-news/rennes-officially-release-statement-on-jeremy-jacquet-surgery/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Milan's Bartesaghi gets green light for Inter clash after injury scare, scan confirms",
    source: "SempreMilan",
    author: "Ben Dixon",
    summary: "Milan's academy graduate Davide Bartesaghi is set for the Derby della Madonnina after his scan showed no injury, prompting Massimiliano Allegri to consider starting him at wing-back.",
    imageUrl: "https://icdn.sempremilan.com/wp-content/uploads/2026/03/Bartesaghi-celebrates.jpg",
    category: "Serie A",
    publishedAt: 1772531409619,
    url: "https://sempremilan.com/bartesaghi-could-start-inter-good-news-scans",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Arsenal press conference LIVE",
    source: "Football London",
    author: "Tom Canton",
    summary: "Arteta faces media scrutiny over Arsenal's set-piece prowess and \"ugliest\" title claims, while Odegaard's fitness and the AMEX challenge dominate the press conference.",
    imageUrl: "https://i2-prod.football.london/incoming/article33521075.ece/ALTERNATES/s1200/0_Mikel-Arteta-and-Arsenal.jpg",
    category: "Arsenal",
    publishedAt: 1772543571000,
    url: "https://www.football.london/arsenal-fc/news/arsenal-press-conference-live-mikel-33521096",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Toni Kroos doubts Arsenal's European charge after recent slip, praises Bayern threat",
    source: "Arsenal Insider",
    author: "Jamie Brown",
    summary: "Kroos tells Einfach mal Luppen he no longer sees Arsenal as clear contenders, citing their dropped Premier League points and City's resurgent form over recent weeks.",
    imageUrl: "https://cdn1.arsenalinsider.com/uploads/19/2026/03/GettyImages-2169800815-1024x683.jpg",
    category: "Champions League",
    publishedAt: 1772536888325,
    url: "https://www.arsenalinsider.com/news/toni-kroos-rates-arsenals-chances-of-winning-the-champions-league-this-season/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Paul Scholes urges Manchester United to move for Carlo Ancelotti after World Cup stint",
    source: "Mirror Football",
    author: "Bruna Reis",
    summary: "Scholes told The Good, The Bad & The Football Podcast: \"Ancelotti is perfect for United where you think he will make players feel a million dollars.\" Carrick's experience still questioned.",
    imageUrl: "https://i2-prod.mirror.co.uk/incoming/article36806847.ece/ALTERNATES/s615/0_Screenshot-2026-03-03-at-081059.png",
    category: "Manchester United",
    publishedAt: 1772528161098,
    url: "https://www.mirror.co.uk/sport/football/news/man-united-carlo-ancelotti-carrick-36806769",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // Top Headlines Articles
  {
    id: crypto.randomUUID(),
    title: "Nick Woltemade a major doubt for Newcastle vs. Man United clash",
    source: "Chronicle Live",
    author: "Lee Ryder",
    summary: "Nick Woltemade is a serious doubt for Newcastle's vital Man United clash due to illness, with Eddie Howe noting, \"We will give him every chance.\" Livramento remains in late-stage rehab.",
    imageUrl: "https://i2-prod.chroniclelive.co.uk/article33514551.ece/ALTERNATES/s1200/0_JS398215070.jpg",
    category: "Premier League",
    publishedAt: 1772530200000,
    url: "https://www.chroniclelive.co.uk/sport/football/football-news/newcastle-united-rocked-nick-woltemade-33519905",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Real Madrid fans demand Florentino Perez's resignation after Getafe defeat",
    source: "Madrid Universal",
    author: "Swapnil",
    summary: "Martin Satriano's lone strike silenced Madrid, sparking rare applause for Getafe and loud calls for Florentino Perez's resignation amid mounting frustration at inconsistent displays.",
    imageUrl: "https://madriduniversal.com/wp-content/uploads/2026/03/real-madrid-cf-v-getafe-cf-laliga-ea-sports-6-1000x600.jpg",
    category: "LaLiga",
    publishedAt: 1772527327070,
    url: "https://madriduniversal.com/santiago-bernabeu-demanded-florentino-perezs-resignation-after-getafe-defeat/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // Manchester United News
  {
    id: crypto.randomUUID(),
    title: "All 10 Premier League Predictions – Week 29",
    source: "Livescore",
    author: "James Milton",
    summary: "James Milton previews all 10 midweek games in the Premier League and offers a score prediction for each clash.",
    imageUrl: "https://images-news.livescore.com/u47hn5mzoiuo/y8zvBWAg1MGaeMCVhiWqg/11fc5991dde6c733964fd4a63a997033/Mikel_Arteta_4.png",
    category: "Premier League",
    publishedAt: 1772462017519,
    url: "https://www.livescore.com/en/news/football/premier-league/predictions/all-10-premier-league-predictions-week-29/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Tyler Adams credits Andoni Iraola for \"simplicity\" as Liverpool and United monitor midfielder",
    source: "Mail Online",
    author: "Daniel Orme",
    summary: "Adams details how Iraola's tactics, shaped by his own experience playing midfield, \"helped me simplify my role to a different level,\" per Men in Blazers Media Network.",
    imageUrl: "https://i.dailymail.co.uk/1s/2026/03/03/13/106830807-0-image-m-8_1772543809798.jpg",
    category: "Manchester United",
    publishedAt: 1772544701450,
    url: "https://www.dailymail.co.uk/sport/football/article-15609889/Bournemouth-star-Andoni-Iraola-Liverpool-Man-United-World-Cup.html",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // Liverpool News
  {
    id: crypto.randomUUID(),
    title: "Wirtz remains sidelined as Slot weighs up Frimpong's minutes before busy Wolves clashes",
    source: "SABC Sport",
    author: "Matthew Appleton",
    summary: "Slot confirmed Wirtz is out but hopes for his return next week, while Frimpong's involvement will be managed following his cameo. Wolves are fully fit, says Rob Edwards, promising a tough contest.",
    imageUrl: "https://cms.sabcsport.com/storage/images/florian-wirtz-31-aug-2025-alamy16_1600x900.webp",
    category: "Liverpool",
    publishedAt: 1772519361700,
    url: "https://www.sabcsport.com/soccer/news/liverpool-juggle-fitness-concerns-ahead-of-wolves-double-header",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Liverpool mull €80m buy-back for Bayer Leverkusen regular Jarell Quansah – 4 goals this season",
    source: "Bulinews",
    author: "Rune Gjerulff",
    summary: "Having impressed with 32 appearances and 4 goals for Leverkusen, Quansah is under close Liverpool watch, with a buy-back clause valid through May 2026, per Sky Germany.",
    imageUrl: "https://bulinews.com/i/320/15420.jpg",
    category: "Liverpool",
    publishedAt: 1772525593387,
    url: "https://bulinews.com/liverpool-considering-activating-80m-buy-back-option-for-leverkusen-jarell-quansah",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Six players set to miss Wolves vs Liverpool after Florian Wirtz update and huge return confirmed",
    source: "Liverpool Echo",
    author: "Kieran Horn",
    summary: "Liverpool take on Wolves in the Premier League this evening with several key players for Arne Slot set to be unavailable through injury",
    imageUrl: "https://i2-prod.football.london/incoming/article33522158.ece/ALTERNATES/s615/0_Florian-Wirtz.jpg",
    category: "Liverpool",
    publishedAt: 1772545007676,
    url: "https://www.liverpoolecho.co.uk/sport/football/football-news/liverpool-injuries-florian-wirtz-wolves-33521561",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // Premier League News
  {
    id: crypto.randomUUID(),
    title: "Which club has the most red cards in a Premier League season?",
    source: "BBC Sport",
    author: "BBC Sport",
    summary: "BBC Sport's Ask Me Anything looks at the record for most red cards in a Premier League season",
    imageUrl: "https://ichef.bbci.co.uk/ace/branded_sport/1200/cpsprodpb/0c47/live/123c8080-1677-11f1-9120-a910fc22c6ac.png",
    category: "Premier League",
    publishedAt: 1772544200993,
    url: "https://www.bbc.com/sport/football/articles/cjdrxl52vvzo",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Brighton boss Fabian Hurzeler takes aim at Arsenal's set-piece tactics ahead of Premier League clash",
    source: "The Independent Football",
    author: "Jamie Gardner and Eleanor Crooks",
    summary: "Fabian Hurzeler has voiced his concerns over set-pieces in the Premier League ahead of Brighton's clash with Arsenal on Wednesday",
    imageUrl: "https://static.independent.co.uk/2026/03/03/13/24/SEI287408462.jpg?width=1200&auto=webp&trim=26%2C0%2C26%2C0",
    category: "Premier League",
    publishedAt: 1772544502511,
    url: "https://www.independent.co.uk/sport/football/arsenal-set-pieces-corners-brighton-hurzeler-b2930995.html",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // Transfer News
  {
    id: crypto.randomUUID(),
    title: "Man Utd, Liverpool circle as Leipzig demand €100m+ for Yan Diomande linking up with Amad Diallo",
    source: "Sports Mole",
    author: "Sports Mole",
    summary: "RB Leipzig want more than €100m for Yan Diomande, urging a United record fee. His bond with Amad Diallo is described as \"selfless\" by Diallo, per Sky Germany's Philipp Hinze.",
    imageUrl: "https://www.sportsmole.co.uk/thumbor/qYXQ40O1x8ke4fZsEpZZsDga8gs=/720x410/smart/filters:format(webp)/https%3A%2F%2Fsportsmole-media-prod.s3.gra.io.cloud.ovh.net%2Fuploads%2F2026%2F03%2Famad-diallo-yan-diomande-email-sportmole-69a69736bea84345002193.png",
    category: "Transfer News",
    publishedAt: 1772528639748,
    url: "https://www.sportsmole.co.uk/football/man-utd/transfer-talk/news/man-utd-now-told-to-pay-record-fee-for-target-amad-diallo-thinks-is-selfless_593107.html",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Andrea Berta zeroes in on Yan Diomande as Arsenal's next left-wing star after Martinelli dip",
    source: "Arsenal Insider",
    author: "Jamie Brown",
    summary: "RB Leipzig's Yan Diomande, 18, is outshining Martinelli and Trossard with 10 goals this term. Leipzig want £87m, but Arsenal and Liverpool are both circling for his electric Bundesliga form.",
    imageUrl: "https://cdn1.arsenalinsider.com/uploads/19/2026/02/GettyImages-2259783956-1024x790.jpg",
    category: "Transfer News",
    publishedAt: 1772529553967,
    url: "https://www.arsenalinsider.com/opinion/after-kenan-yildiz-andrea-bertas-ideal-gabriel-martinelli-replacement-at-arsenal-is-now-so-clear/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Chelsea plot cheeky Micky van de Ven, Kudus and Gallagher swoop if Spurs fall",
    source: "The Chelsea Chronicle",
    author: "Jack Drury",
    summary: "Spurs' battle near the bottom may spark a dramatic exodus. Chelsea Chronicle names Van de Ven, Kudus and Gallagher as priorities, citing wage cuts and healing fan heartache.",
    imageUrl: "https://cdn1.thechelseachronicle.com/uploads/17/2026/03/GettyImages-2263704285-1024x741.jpg",
    category: "Transfer News",
    publishedAt: 1772517867162,
    url: "https://www.thechelseachronicle.com/columnist/fire-sale-incoming-three-spurs-players-chelsea-should-sign-if-they-get-relegated-this-season/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Tottenham consider Lens' Robin Risser as recruitment look to future beyond Vicario",
    source: "CaughtOffside",
    author: "Ahad Shaukat",
    summary: "Spurs' chiefs rate Risser for his calm in possession and leadership, with Nottingham Forest and Newcastle also keen. Lens will resist, but a €10m fee keeps him on Tottenham's radar.",
    imageUrl: "https://icdn.caughtoffside.com/wp-content/uploads/2026/02/COS-FeaturedHero-Image-Templates-2-5.jpg",
    category: "Transfer News",
    publishedAt: 1772518772647,
    url: "https://www.caughtoffside.com/2026/03/03/sources-tottenham-reshuffle-goalkeeping-department/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Alisson attracts Inter and Juventus, Man Utd chase Guimarães as Casemiro alternative",
    source: "Transfermarkt",
    author: "Redaktion Transfermarkt",
    summary: "Inter Milan and Juventus reportedly pursue Liverpool's Alisson for a summer switch, while Man Utd consider Newcastle's Bruno Guimarães to replace Casemiro, per latest transfer rumours.",
    imageUrl: "https://tmssl.akamaized.net/images/foto/big/casemiro-manchester-united-2026-imago1071362612-1769101291-187820.jpg?lm=1769101298",
    category: "Transfer News",
    publishedAt: 1772525680815,
    url: "https://www.transfermarkt.co.uk/transfer-news-live-serie-a-duo-want-liverpool-star-man-utd-find-casemiro-replacement/view/news/445145",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // Arsenal News
  {
    id: crypto.randomUUID(),
    title: "Sagna warns Ben White faces Arsenal crossroads as Everton, Barcelona links emerge",
    source: "Sports Mole",
    author: "Sports Mole",
    summary: "Sagna tells Sports Mole Ben White must pick club or country ambitions, citing competition from Timber and European interest. Injury woes may force a tough summer decision.",
    imageUrl: "https://www.sportsmole.co.uk/thumbor/SsSfBBhlwSdEo10V48ToCDOfOHE=/720x410/smart/filters:format(webp)/https%3A%2F%2Fsportsmole-media-prod.s3.gra.io.cloud.ovh.net%2Fuploads%2F2026%2F03%2Farne-slot-mo-salah-correspondent-email-sportmole-5-69a6b053c957f408845169.jpg",
    category: "Arsenal",
    publishedAt: 1772535966300,
    url: "https://www.sportsmole.co.uk/football/arsenal/transfer-talk/news/exclusive-sagna-delivers-white-arsenal-transfer-verdict-after-latest-injury-blow_593091.html",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // LaLiga News
  {
    id: crypto.randomUUID(),
    title: "Arbeloa rages at Mastantuono red as Madrid lose to Getafe, fall behind Barça",
    source: "SABC Sport",
    author: "SABC Sport",
    summary: "Arbeloa accepted blame for defeat, praised his players' fight, and called Mastantuono's dismissal \"unacceptable\" after Satriano's goal ended Getafe's Bernabeu drought.",
    imageUrl: "https://cms.sabcsport.com/storage/images/getafe-cf-s-martin-satriano-celebrates-scoring-2-march-202616_1600x900.webp",
    category: "LaLiga",
    publishedAt: 1772519361700,
    url: "https://www.sabcsport.com/soccer/news/alvaro-arbeloa-fumes-after-shock-getafe-defeat-as-real-madrid-stumble-in-title-race",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "The exact words that got Real Madrid starlet sent off against Getafe: 'What a shame…'",
    source: "Madrid Universal",
    author: "Swapnil",
    summary: "It was a frustrating night for Real Madrid, and it ended in the worst possible way for one of their brightest young talents. Teenage starlet Franco Mastantuono was sent off in the closing stages of the 0-1 defeat to Getafe.",
    imageUrl: "https://madriduniversal.com/wp-content/uploads/2026/03/real-madrid-cf-v-getafe-cf-laliga-ea-sports-3-1000x600.jpg",
    category: "LaLiga",
    publishedAt: 1772525165286,
    url: "https://madriduniversal.com/the-exact-words-that-got-real-madrid-starlet-sent-off-against-getafe-what-a-shame/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Flick and Deco finalise summer exits: Cancelo, Casado and Bardghji set to leave Barça",
    source: "Barça Universal",
    author: "Swapnil Bhopatkar",
    summary: "Fichajes reports Flick wants Cancelo gone after loan, values Casado's work ethic but questions his influence, and may loan or sell Bardghji due to Lamine Yamal's rising status.",
    imageUrl: "https://barcauniversal.com/wp-content/uploads/2026/02/girona-fc-v-fc-barcelona-laliga-ea-sports-9-1000x600.jpg",
    category: "LaLiga",
    publishedAt: 1772525126878,
    url: "https://barcauniversal.com/barcelona-manager-picks-three-names-for-summer-clear-out-report/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Major concern – Real Madrid could be without ten players against Celta Vigo",
    source: "Madrid Universal",
    author: "Swapnil",
    summary: "Real Madrid are once again dealing with a worrying injury situation, and this time it could seriously affect their trip to Vigo. According to reports from Abraham Romero of El Mundo, as many as 10 players could miss Friday's La Liga clash against Celta de Vigo at Balaidos due to a mix of injuries.",
    imageUrl: "https://madriduniversal.com/wp-content/uploads/2026/02/ca-osasuna-v-real-madrid-cf-laliga-ea-sports-2-1000x600.jpg",
    category: "LaLiga",
    publishedAt: 1772544708430,
    url: "https://madriduniversal.com/major-concern-real-madrid-could-be-without-ten-players-against-celta-vigo/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Endrick eclipses Mbappe and Messi's debut form, lighting up Lyon with early heroics",
    source: "Madrid Universal",
    author: "Swapnil",
    summary: "Endrick has notched 3 goals and 3 assists in his first 6 Ligue 1 games, outpacing Mbappe's and Messi's opening records, per Mundo Deportivo. Neymar's debut tally still stands superior.",
    imageUrl: "https://madriduniversal.com/wp-content/uploads/2026/02/real-madrid-cf-v-getafe-cf-laliga-ea-sports-6-1000x600.jpg",
    category: "LaLiga",
    publishedAt: 1772543822447,
    url: "https://madriduniversal.com/real-madrid-loanee-explodes-in-france-surpasses-mbappe-and-messis-start/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // Fantasy Football
  {
    id: crypto.randomUUID(),
    title: "Man City v Nott'm Forest predicted line-ups + FPL team news",
    source: "Fantasy Football Scout",
    author: "FPL Marc",
    summary: "Team form, absentees and our predicted XIs The post Man City v Nott'm Forest predicted line-ups + FPL team news appeared first on Best FPL Tips, Advice, Team News, Picks, and Statistics from Fantasy Football Scout.",
    imageUrl: "https://cdn.fantasyfootballscout.co.uk/wp-content/uploads/2025/03/leicester-v-man-united-fpl-team-news-predicted-line-ups.jpg",
    category: "Fantasy Football",
    publishedAt: 1772545186686,
    url: "https://www.fantasyfootballscout.co.uk/2026/03/03/man-city-v-nottm-forest-predicted-line-ups-fpl-team-news/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Guardiola stays vague on Haaland and O'Reilly as FPL managers weigh risks for GW29",
    source: "Fantasy Football Scout",
    author: "FPL Marc",
    summary: "Guardiola says Haaland \"feels much better,\" but decisions on his and O'Reilly's availability will happen post-training, offering little certainty ahead of Forest.",
    imageUrl: "https://cdn.fantasyfootballscout.co.uk/wp-content/uploads/2026/02/fpl-notes-haaland-bonus-semenyo-defcon-oreilly-deserves-minutes-2.jpg",
    category: "Fantasy Football",
    publishedAt: 1772542962871,
    url: "https://www.fantasyfootballscout.co.uk/2026/03/03/haaland-oreilly-man-city-injury-latest-for-fpl-gameweek-29/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "FPL Rate My Team surgery with five-time top 1k finisher Tom Freeman",
    source: "Fantasy Football Scout",
    author: "avfc82",
    summary: "Ask your questions before Tuesday's deadline The post FPL Rate My Team surgery with five-time top 1k finisher Tom Freeman appeared first on Best FPL Tips, Advice, Team News, Picks, and Statistics from Fantasy Football Scout.",
    imageUrl: "https://cdn.fantasyfootballscout.co.uk/wp-content/uploads/2026/03/fpl-rate-my-team-surgery-with-five-time-top-1k-finisher-tom-freeman-84.jpg",
    category: "Fantasy Football",
    publishedAt: 1772541228557,
    url: "https://www.fantasyfootballscout.co.uk/2026/03/03/fpl-rate-my-team-surgery-with-five-time-top-1k-finisher-tom-freeman-84/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Tottenham likely stick with Son up top as Palace weigh late defensive tweaks",
    source: "Fantasy Football Scout",
    author: "FPL Marc",
    summary: "Predicted XIs suggest Son Heung-min leads Spurs' attack while Palace assess their back line post-press conference, with xGI stats spotlighting key FPL options for Gameweek 29.",
    imageUrl: "https://cdn.fantasyfootballscout.co.uk/wp-content/uploads/2025/03/leicester-v-man-united-fpl-team-news-predicted-line-ups.jpg",
    category: "Fantasy Football",
    publishedAt: 1772540800249,
    url: "https://www.fantasyfootballscout.co.uk/2026/03/03/tottenham-v-crystal-palace-predicted-line-ups-fpl-team-news/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Wolves face resurgent Liverpool at Molineux as FPL managers eye Salah and Neto calls",
    source: "Fantasy Football Scout",
    author: "FPL Marc",
    summary: "Predicted XIs reveal Salah returns to the fold for Liverpool, while Neto leads Wolves' hope. Recent FPL form casts Reds as clear favourites for Gameweek 29 points haul.",
    imageUrl: "https://cdn.fantasyfootballscout.co.uk/wp-content/uploads/2025/03/leicester-v-man-united-fpl-team-news-predicted-line-ups.jpg",
    category: "Fantasy Football",
    publishedAt: 1772540800249,
    url: "https://www.fantasyfootballscout.co.uk/2026/03/03/wolves-v-liverpool-predicted-line-ups-fpl-team-news/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // Championship
  {
    id: crypto.randomUUID(),
    title: "Sydie Peck shines for Blades as Ali Maxwell hails him 'very, very exciting' after QPR win",
    source: "The72 - All Leagues",
    author: "Harry Mail",
    summary: "Ali Maxwell raves about Sydie Peck's rise, noting his increasing confidence and incisiveness: \"He's certainly standing out at the moment,\" per Not The Top 20 Podcast.",
    imageUrl: "https://cdn.the72.co.uk/wp-content/uploads/2026/03/ltKDv5SVLOod-900x617.webp",
    category: "Championship",
    publishedAt: 1772544822890,
    url: "https://the72.co.uk/2026/03/03/sheffield-united-sydie-peck-hailed-qpr-win-ali-maxwell/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Leicester unveil James McCarron as sporting director amid fan protests and club overhaul",
    source: "BBC Sport",
    author: "BBC Sport",
    summary: "McCarron joins from Lommel after Foxes' fourth home loss, tasked with revamping performance and trading. Jon Rudkin steps up as chief football officer; Kevin Davies becomes CEO.",
    imageUrl: "https://ichef.bbci.co.uk/ace/branded_sport/1200/cpsprodpb/5823/live/639d97e0-16ff-11f1-9120-a910fc22c6ac.jpg",
    category: "Championship",
    publishedAt: 1772543723077,
    url: "https://www.bbc.com/sport/football/articles/cx28w19vpg5o",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Lewis Miller opens up on Achilles injury, missed World Cup and difficult rehab journey",
    source: "Lancashire Telegraph - Blackburn Rovers",
    author: "Elliott Jackson",
    summary: "Miller describes the moment his Achilles ruptured as feeling \"like a gunshot – it popped,\" per RoversTV. He focuses on chess and reading to stay positive during rehab.",
    imageUrl: "https://www.lancashiretelegraph.co.uk/resources/images/20606671/",
    category: "Championship",
    publishedAt: 1772542796785,
    url: "https://www.lancashiretelegraph.co.uk/sport/25902232.millers-world-cup-heartbreak-blackburn-rovers-injury/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Chris Davies brands Birmingham City's defence \"a bit of a mess\" after limp Middlesbrough loss",
    source: "The72 - All Leagues",
    author: "Humzah Mudhir",
    summary: "Davies blamed poor decision-making and defensive lapses, lamenting, \"The second goal really rocked us, we just struggled to get going again,\" per The72. Play-off hopes falter further.",
    imageUrl: "https://cdn.the72.co.uk/wp-content/uploads/2026/02/The72-default-image-e1772205018644.png",
    category: "Championship",
    publishedAt: 1772542615997,
    url: "https://the72.co.uk/2026/03/03/birmingham-city-chris-davies-assessment-boro-defeat/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Swansea brace for Zan Vipotnik bids as £15m price tag put on prolific striker",
    source: "The72 - All Leagues",
    author: "James Ray",
    summary: "Slovenian star Zan Vipotnik has hit 18 goals for Swansea this term, sparking rumours of a summer move. The club have set a £15m valuation amid uncertain contract talks.",
    imageUrl: "https://cdn.the72.co.uk/wp-content/uploads/2026/02/The72-default-image-e1772205018644.png",
    category: "Championship",
    publishedAt: 1772540465927,
    url: "https://the72.co.uk/2026/03/03/swansea-city-zan-vipotnik-transfer-rumours/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // Serie A
  {
    id: crypto.randomUUID(),
    title: "Arsenal, Manchester City and Barcelona join chase for Inter's Alessandro Bastoni at £87m",
    source: "Arsenal Station",
    author: "Ritayan Chatterjee",
    summary: "Bastoni's 8 goals and 10 clean sheets fuel transfer rumours, but Inter aim to extend his deal past 2028 and may demand more than £87m, according to Caught Offside.",
    imageUrl: "https://www.arsenalstation.com/wp-content/uploads/2026/02/20260216_231614-ezgif.com-resize.jpg",
    category: "Serie A",
    publishedAt: 1772521723180,
    url: "https://www.arsenalstation.com/2026/03/03/arsenal-plot-ambitious-swoop-to-sign-alessandro-bastoni/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Inter and Juventus circle Alisson as United fancy Bruno Guimaraes for summer shake-up",
    source: "BBC Sport",
    author: "BBC Sport",
    summary: "Inter Milan and Juventus are pursuing Liverpool's Alisson, while Man United want Bruno Guimaraes with Casemiro's blessing, and Arsenal top the race for Leon Goretzka's PL dream move.",
    imageUrl: "https://ichef.bbci.co.uk/ace/branded_sport/1200/cpsprodpb/9c47/live/973c8080-1677-11f1-9120-a910fc22c6ac.png",
    category: "Serie A",
    publishedAt: 1772530207509,
    url: "https://www.bbc.com/sport/football/articles/czx4375dx5go",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Arsenal Open Talks to Sign Inter Milan Star Pio Esposito, Arteta Wants Him",
    source: "GiveMeSport",
    author: "Laurynas Puikys",
    summary: "Arsenal have stepped up their interest in Inter Milan striker Pio Esposito.",
    imageUrl: "https://static0.givemesportimages.com/wordpress/wp-content/uploads/2025/12/mikel-arteta-arsenal.jpg",
    category: "Serie A",
    publishedAt: 1772543970898,
    url: "https://www.givemesport.com/arsenal-open-talks-pio-esposito-inter-milan-transfer-news/",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "'Maximum confidence and space' – Moretto reveals why Milan management rejected Disasi move",
    source: "SempreMilan",
    author: "Ben Dixon",
    summary: "By: Ben Dixon AC Milan were quite open to making a move for Axel Disasi in January. Yet, the Frenchman did not arrive at Milanello. It was clear throughout January that Milan were keen to add a defender to the squad.",
    imageUrl: "https://icdn.sempremilan.com/wp-content/uploads/2026/03/Disasi-Milan-cross.jpg",
    category: "Serie A",
    publishedAt: 1772543555849,
    url: "https://sempremilan.com/moretto-reveals-why-milan-said-no-disasi",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  // Champions League
  {
    id: crypto.randomUUID(),
    title: "Real Madrid suffer triple suspension blow ahead of Man City Champions League clash",
    source: "Evening Standard Football",
    author: "Tashan Deniran-Alleyne",
    summary: "Los Blancos also sweating on fitness of Kylian Mbappe after losing ground in LaLiga title race",
    imageUrl: "https://static.standard.co.uk/2026/03/03/8/54/AlvaroArbeloaRealMadrid03032026.jpeg?width=1200&auto=webp&crop=3%3A2",
    category: "Champions League",
    publishedAt: 1772526898531,
    url: "https://www.standard.co.uk/sport/football/real-madrid-suspension-blow-man-city-champions-league-b1273201.html",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Liverpool and rivals' run-ins analysed as unlikely Champions League contender emerges",
    source: "Liverpool Echo",
    author: "Matthew Appleton",
    summary: "A look at the remaining fixtures of the five Premier League clubs in a fierce battle to secure Champions League football next season",
    imageUrl: "https://i2-prod.liverpool.com/incoming/article33437212.ece/ALTERNATES/s615/1_GettyImages-2242244222.jpg",
    category: "Champions League",
    publishedAt: 1772538060874,
    url: "https://www.liverpoolecho.co.uk/sport/football/football-news/liverpool-rivals-run-ins-analysed-33521057",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Rodri future, Vinicius standoff and Elliot Anderson chase fuel City–Madrid rivalry",
    source: "Sports Mole",
    author: "Sports Mole",
    summary: "Guardiola's desire to keep Rodri faces Madrid pressure, while City watch Vinicius amid contract tension. Anderson emerges as a shared £51m target for both sides this summer.",
    imageUrl: "https://www.sportsmole.co.uk/thumbor/lx5rGrEOXpBBv0oukdict9N9Ezc=/720x410/smart/filters:format(webp)/https%3A%2F%2Fsportsmole-media-prod.s3.gra.io.cloud.ovh.net%2Fuploads%2F2026%2F03%2Fimago1073070254-1-69a6a917e23f7225287020.jpg",
    category: "Champions League",
    publishedAt: 1772532055551,
    url: "https://www.sportsmole.co.uk/football/man-city/transfer-talk/news/three-transfer-battles-set-to-ignite-city-vs-real-madrid-champions-league-clash_593111.html",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Diogo Dalot rallies Man Utd after Carrick's Premier League charge: Champions League focus",
    source: "Mirror Football",
    author: "Daniel Orme",
    summary: "Dalot pushes teammates to seek Champions League, saying, \"When we get the main goal…if we're playing Champions League, we cannot take for granted.\" per The Mirror.",
    imageUrl: "https://i2-prod.mirror.co.uk/incoming/article36806046.ece/ALTERNATES/s615/0_GettyImages-2263726423.jpg",
    category: "Champions League",
    publishedAt: 1772485303935,
    url: "https://www.mirror.co.uk/sport/football/news/man-united-fernandes-dalot-carrick-36806056",
    likes: 0,
    comments: 0,
    bookmarks: 0,
  },
];

// Trending articles (top 10 for Trends component)
export const trendingArticles = articlesData.slice(0, 10);

// Helper function to get article by ID
export function getArticleById(id: string): Article | undefined {
  return articlesData.find((article) => article.id === id);
}

// Helper function to update engagement metrics
export function updateArticleEngagement(
  id: string,
  type: "like" | "comment" | "bookmark",
  increment: boolean = true
): void {
  const article = getArticleById(id);
  if (article) {
    if (type === "like") {
      article.likes += increment ? 1 : -1;
    } else if (type === "comment") {
      article.comments += increment ? 1 : -1;
    } else if (type === "bookmark") {
      article.bookmarks += increment ? 1 : -1;
    }
  }
}